import { Resend } from "resend";
import type { AiTriageResult } from "@/types/incident";

const TOP_TIERS = new Set(["First Class", "Platinum"]);

interface EscalationContext {
  incidentId: string;
  staffName: string;
  rawText: string;
  triage: AiTriageResult;
}

export function shouldEscalate(triage: AiTriageResult): boolean {
  return (
    triage.urgency === "Critical" &&
    triage.confidence_score > 0.8 &&
    TOP_TIERS.has(triage.client_tier)
  );
}

export async function sendEscalationEmail(
  ctx: EscalationContext
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.warn("RESEND_API_KEY not set — skipping escalation email");
    return;
  }

  const resend = new Resend(apiKey);
  const toAddress =
    process.env.ESCALATION_EMAIL_TO || "duty-manager@omnilink.vip";
  const fromAddress =
    process.env.ESCALATION_EMAIL_FROM || "alerts@omnilink.vip";

  await resend.emails.send({
    from: fromAddress,
    to: toAddress,
    subject: `🚨 CRITICAL VIP INCIDENT — ${ctx.triage.client_tier} / ${ctx.triage.issue_type}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px;">
        <h2 style="color: #dc2626;">Critical VIP Incident Alert</h2>
        <table style="width:100%; border-collapse:collapse;">
          <tr><td style="padding:8px; font-weight:bold;">Incident ID</td><td style="padding:8px;">${ctx.incidentId}</td></tr>
          <tr><td style="padding:8px; font-weight:bold;">Reported By</td><td style="padding:8px;">${ctx.staffName}</td></tr>
          <tr><td style="padding:8px; font-weight:bold;">Client Tier</td><td style="padding:8px;">${ctx.triage.client_tier}</td></tr>
          <tr><td style="padding:8px; font-weight:bold;">Issue Type</td><td style="padding:8px;">${ctx.triage.issue_type}</td></tr>
          <tr><td style="padding:8px; font-weight:bold;">Urgency</td><td style="padding:8px; color:#dc2626; font-weight:bold;">${ctx.triage.urgency}</td></tr>
          <tr><td style="padding:8px; font-weight:bold;">Confidence</td><td style="padding:8px;">${(ctx.triage.confidence_score * 100).toFixed(0)}%</td></tr>
        </table>
        <h3>AI Suggested Action</h3>
        <p style="background:#fef2f2; padding:12px; border-left:4px solid #dc2626;">${ctx.triage.suggested_action}</p>
        <h3>AI Reasoning</h3>
        <p style="background:#f9fafb; padding:12px; border-left:4px solid #6b7280;">${ctx.triage.reasoning}</p>
        <h3>Raw Report</h3>
        <p style="background:#f9fafb; padding:12px; font-style:italic;">${ctx.rawText}</p>
        <hr />
        <p style="color:#6b7280; font-size:12px;">This alert was auto-generated by OmniLink VIP Gateway. Review and take action on the Operations Dashboard.</p>
      </div>
    `,
  });
}
